from tkinter import*
from tkinter.filedialog import*
screen=Tk()
screen.configure(bg="black")
l1=Label(screen,text="My Adress Book",fg="WHITE")
b1=Button(screen,text="OPEN",background="BLACK",fg="WHITE")
list1=Listbox(screen,height=15,width=25)
l2=Label(screen,text="Name",background="BLACK",fg="WHITE")
l3=Label(screen,text="Adress",background="BLACK",fg="WHITE")
l4=Label(screen,text="Email",background="BLACK",fg="WHITE")
l5=Label(screen,text="Mobile",background="BLACK",fg="WHITE")
l6=Label(screen,text="Birthday",background="BLACK",fg="WHITE")
c2=Entry(screen,background="BLACK",fg="WHITE")
c3=Entry(screen,background="BLACK",fg="WHITE")
c4=Entry(screen,background="BLACK",fg="WHITE")
c5=Entry(screen,background="BLACK",fg="WHITE")
c6=Entry(screen,background="BLACK",fg="WHITE")
b2=Button(screen,text="Edit",background="BLACK",fg="WHITE")
b3=Button(screen,text="Delete",background="BLACK",fg="WHITE")
b4=Button(screen,text="Update",background="BLACK",fg="WHITE")
b5=Button(screen,text="Save",background="BLACK",fg="WHITE")

l1.grid(row=0,column=1)
b1.grid(row=0,column=2)
l2.grid(row=1,column=1)
l3.grid(row=2,column=1)
l4.grid(row=3,column=1)
l5.grid(row=4,column=1)
l6.grid(row=5,column=1)
c2.grid(row=1,column=2)
c3.grid(row=2,column=2)
c4.grid(row=3,column=2)
c5.grid(row=4,column=2)
c6.grid(row=5,column=2)
list1.grid(row=2,column=0,columnspan=3, rowspan=5)

screen.mainloop()