from tkinter import*
s=Tk()
s.config(background="lightblue")
s.geometry("350x200")
l1=Label(s,text="Chocos and IceCreams",font=("Cambria",15)).pack()
f1=Frame(s).pack()
f2=Frame(s).pack(side=BOTTOM)
b1=Button(f1,text="Choco",background="beige",fg="red").place(x=77,y=50)
b2=Button(f1,text="Dark Choco",background="beige",fg="red").place(x=122,y=50)
b3=Button(f1,text="White Choco",background="beige",fg="red").place(x=194,y=50)
b4=Button(f2,width=15,text="Tiramisu",background="silver",fg="beige").pack(side=BOTTOM)
b5=Button(f2,width=15,text="Cake",background="silver",fg="beige").pack(side=BOTTOM)
b6=Button(f2,width=15,text="Pastry",background="silver",fg="beige").pack(side=BOTTOM)
s.mainloop()