from tkinter import*
s=Tk()
s.geometry("500x650")
s.config(background="white")
b1=Button(s,width=38,text="CREATE ACOUNT",fg="white",background="blue",command=s.destroy).place(x=100,y=500)
b2=Button(s,width=1,text="✓",background="grey",).place(x=100,y=445)
b3=Button(s,width=25,text="HAVE AN ACOUNT? CLICK HERE",background="white",command=s.destroy).place(x=140,y=540)
l1=Label(s,text="SIGN UP",font=("arial",36),background="WHITE",foreground="black").place(x=140,y=50)
l2=Label(s,text="USERNAME",font=("arial",7),background="WHITE",foreground="black").place(x=105,y=180)
l3=Label(s,text="EMAIL ADDRESS",font=("arial",7),background="WHITE",foreground="black").place(x=105,y=280)
l4=Label(s,text="PASSWORD",font=("arial",7),background="WHITE",foreground="black").place(x=105,y=380)
l4=Label(s,height=2,text="I agree to the terms and conditions",font=("arial",8),background="white",foreground="black").place(x=115,y=445)
c1=Entry(s,width=15,background="grey",font=("cambria",25),foreground="black").place(x=100,y=200)
c2=Entry(s,width=15,background="grey",font=("cambria",25),foreground="black").place(x=100,y=300)
c3=Entry(s,width=15,background="grey",font=("cambria",25),foreground="black").place(x=100,y=400)
s.mainloop()