from tkinter import*
s=Tk ()
s.geometry("800x600")
s.config(background="pink") 
l1=Label(s,background="pink",text="Username",font=("cambria",40)).place(x=50, y=50)
l2=Label(s,background="pink",text="Password",font=("cambria",40)).place(x=50, y=150)
c1=Entry(s,bg="white",fg="black",width=15,font=("cambria",40)).place(x=300, y=50)
c2=Entry(s,bg="white",fg="black",width=15,font=("cambria",40)).place(x=300, y=150)
b2=Button(s,width=50,height=5,text="submit",background="white",font=("cambria",15),command=s.destroy).place(x=100,y=350)
s.mainloop()
