from tkinter import*
s=Tk()
l1=Label(s,text="Enter the weight in KG",font=("cambria",25),background="black",foreground="yellow")
c1=Entry(s,width=10,background="white",font=("cambria",25),foreground="black")
b1=Button(s,text="Convert",background="grey")
l2=Label(s,text="GRAM",font=("cambria",25),background="black",foreground="yellow")
l3=Label(s,text="POUNDS",font=("cambria",25),background="black",foreground="yellow")
l4=Label(s,text="OUNCE",font=("cambria",25),background="black",foreground="yellow")
t1=Text(s,height=1,width=10)
t2=Text(s,height=1,width=10)
t3=Text(s,height=1,width=10)
l1.grid(row=0,column=0)
c1.grid(row=0,column=1)
b1.grid(row=0,column=2)
l2.grid(row=1,column=0)
l3.grid(row=1,column=1)
l4.grid(row=1,column=2)
t1.grid(row=2,column=0)
t2.grid(row=2,column=1)
t3.grid(row=2,column=2)
s.mainloop()
